[project]
name = "brpyople"
version = "0.0.0" # Só será útil quando o pacote for subido para o PyPI
requires-python = ">=3.0"
dependencies = []

[project.optional-dependencies]
testes = [
    "pytest~=8.3",
    "mypy~=1.10",
    "pylint~=3.2"
]
